name: "GitHUb Action"

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Npm install
        run: npm run install

      - name: Building
        run: npm run build
  
