name: "GitHUb Action"

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Formatting
        run: npm run format

      - name: Building
        run: npm run build
  
